const prompts=[
{topic:"Do you think more people will work from home in the future?",points:["Time","Family","Technology"],model:"I think that more people will work from home in the future. I have two reasons. First, working from home saves time because people do not have to travel to their offices. They can use this extra time for their families or hobbies. Second, technology is becoming better. People can easily have online meetings and share information with coworkers. For these reasons, I believe working from home will become more common."},
{topic:"Should students use tablets instead of textbooks at school?",points:["Convenience","Cost","Learning"],model:"I think students should use tablets at school. First, tablets are convenient because students can carry many books in one small device. Their school bags will be much lighter. Second, tablets can make learning more interesting. Students can watch videos and use educational applications during class. Although tablets can be expensive, they are useful in many ways. Therefore, I think schools should use them more often."},
{topic:"Do you think cities should have more parks?",points:["Health","Environment","Community"],model:"I think cities should have more parks. First, parks give people places to exercise and relax. This is good for both their physical and mental health. Second, trees and plants in parks help improve the environment. They can make the air cleaner and keep cities cooler in summer. Parks are also places where neighbors can meet. For these reasons, I believe more parks will make cities better places to live."}
];
const $=s=>document.querySelector(s);let modelOpen=false;
$("#promptSelect").innerHTML=prompts.map((_,i)=>`<option value="${i}">お題 ${i+1}</option>`).join("");
function loadPrompt(){const p=prompts[Number($("#promptSelect").value)];$("#writingTopic").textContent=p.topic;$("#writingPoints").innerHTML=p.points.map(x=>`<li>${x}</li>`).join("");$("#modelText").textContent=p.model;modelOpen=false;$("#modelAnswer").hidden=true;$("#modelToggle").textContent="模範解答を見る"}
function count(){const text=$("#essay").value.trim();const n=text?text.split(/\s+/).length:0;$("#wordCount").textContent=`${n} words`;$("#countGuide").textContent=n<80?`あと${80-n}語で目標に到達`:n<=100?"目標語数に達しています":`目標より${n-100}語多いです`;$("#countGuide").className=n>=80&&n<=100?"count-guide on-target":"count-guide"}
$("#promptSelect").addEventListener("change",loadPrompt);$("#essay").addEventListener("input",count);$("#modelToggle").addEventListener("click",()=>{modelOpen=!modelOpen;$("#modelAnswer").hidden=!modelOpen;$("#modelToggle").textContent=modelOpen?"模範解答を閉じる":"模範解答を見る"});loadPrompt();count();
